### ISSUE TITLE
does this support sm-n950u1 ?

### ISSUE THREAD

**Issue by excitedbrent** [ivanmeler/android_kernel_samsung_universal8895#1]
dear developer, I checked https://forum.xda-developers.com/galaxy-note-8/development/rom-lineageos-15-1-t3899831 , just can't tell if this support n950u1 since n950u cpu is Qualcomm MSM8998 Snapdragon 835 while n950f is Exynos 8895 Octa.  

 I THINK the answer is no. :)

**Comment by Stricted** [comment]
https://www.sammobile.com/samsung/galaxy-note-8/specs/SM-N950U1/
since its a snapdragon nope it wont work
